// Slug conversion — matches skill rules: lowercase, hyphens, strip special chars
export function toSlug(input) {
  return (input || '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
}

// snake_case ACF field name from a label
export function toFieldName(label) {
  return (label || '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s_]/g, '')
    .replace(/\s+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '')
}

// PascalCase for namespace fallback etc
export function toPascal(input) {
  return (input || '')
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .split(/\s+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
}

// Auto-detect block libraries from name (keyword match per skill)
export function detectLibraries(blockName) {
  const n = (blockName || '').toLowerCase()
  return {
    tabs: /\btab(s|ulation)?\b/.test(n),
    slider: /\b(slider|carousel)\b/.test(n),
    accordion: /\b(accordion|faq)\b/.test(n),
  }
}

// Generate a 16-char hex string. Cryptographically random per call so keys
// are globally unique across blocks generated by this app — matches skill's
// "never reuse a hex string" requirement.
export function hex16() {
  const bytes = new Uint8Array(8)
  if (typeof crypto !== 'undefined' && crypto.getRandomValues) {
    crypto.getRandomValues(bytes)
  } else {
    for (let i = 0; i < 8; i++) bytes[i] = Math.floor(Math.random() * 256)
  }
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('')
}

export const fieldKey = () => `field__${hex16()}`
export const groupKey = () => `group__${hex16()}`

// Stable unique id for React lists (different from ACF field key — internal only)
export function uid() {
  return Math.random().toString(36).slice(2, 10)
}
