import JSZip from 'jszip'
import { generateBlockJson } from './blockJson.js'
import { generateFieldsPhp } from './fieldsPhp.js'
import { generateRenderPhp } from './renderPhp.js'
import { generateBlockCss } from './blockCss.js'
import { generateBlockJs } from './blockJs.js'

export function generateAllFiles(schema) {
  const blockJson = generateBlockJson(schema)
  const fieldsPhpResult = generateFieldsPhp(schema)
  const renderPhp = generateRenderPhp(schema)
  const blockCss = generateBlockCss(schema)
  const blockJs = generateBlockJs(schema)

  return {
    'block.json': blockJson,
    'fields.php': fieldsPhpResult.code,
    'template.php': renderPhp,
    'stylesheet.css': blockCss,
    ...(blockJs ? { 'block.js': blockJs } : {}),
  }
}

export async function buildZip(schema) {
  const files = generateAllFiles(schema)
  const zip = new JSZip()
  // Single folder at the ZIP root: just `{slug}/`. The user moves this folder
  // into their theme's existing `gutenberg-blocks/` directory — no
  // doubled-folder traps regardless of how the OS auto-extracts.
  const folder = zip.folder(schema.slug)

  for (const [name, content] of Object.entries(files)) {
    folder.file(name, content)
  }

  // Bundle a README describing how to install
  const readme = `# ${schema.title}

ACF Pro Gutenberg block generated by acf-block-generator.

## Install

1. Move this entire \`${schema.slug}/\` folder into your theme at: \`{theme}/gutenberg-blocks/${schema.slug}/\`
   (final path inside the theme should be exactly that — never \`gutenberg-blocks/${schema.slug}/${schema.slug}/\`).
2. Make sure the block loader is registered in \`functions.php\` (see snippet below).
3. Activate ACF Pro on the site.
4. The block will appear in the block inserter under the "Theme" category.

## Block loader (add once to functions.php)

\`\`\`php
add_action( 'init', function () {
    $blocks_dir = get_template_directory() . '/gutenberg-blocks/';
    if ( ! is_dir( $blocks_dir ) ) return;

    foreach ( glob( $blocks_dir . '*', GLOB_ONLYDIR ) as $block_path ) {
        if ( file_exists( $block_path . '/block.json' ) ) {
            register_block_type( $block_path );
        }
        if ( file_exists( $block_path . '/fields.php' ) ) {
            require_once $block_path . '/fields.php';
        }
    }
} );
\`\`\`${schema.options?.hasGlobalSettings ? `

## Global Settings (Section Globals)

This block registers itself as a **sub-page** under a shared **"Section Globals"** parent menu in WP Admin. Every block built with this generator that has Global Settings turned on becomes a sub-page under the same parent — editors get one tidy menu instead of one menu per block.

### Zero functions.php changes required

The parent "Section Globals" page is auto-registered inside this block's \`fields.php\` using a \`function_exists()\` guard. Whichever block's \`fields.php\` runs first defines the registration function and registers the parent page; later blocks see the function exists and skip the redefinition. Because your existing block loader already does \`require_once($path . 'fields.php')\`, **no functions.php edits are needed**.

### How it works

- Sub-page menu slug for this block: \`${schema.slug}-globals\` (under parent \`section-global-settings\`).
- The block has a master \`use_global_settings\` toggle (default: ON).
- When the toggle is ON, \`template.php\` reads every value from the options page via \`get_field( name, 'option' )\`.
- When the toggle is OFF, the block uses its own per-page values (override).

To rename this block's sub-page, edit the \`page_title\` / \`menu_title\` keys in the global-settings block at the bottom of \`fields.php\`. The \`parent_slug\` must stay \`section-global-settings\` to keep blocks grouped under the same menu.` : ''}

## Files

${Object.keys(files).map((f) => `- \`${f}\``).join('\n')}
`

  folder.file('README.md', readme)

  return zip.generateAsync({ type: 'blob' })
}

export function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
